site_name: Cours de Maths
#site_url: https://<ton-utilisateur>.github.io/<nom-du-repo>/
#repo_url: https://github.com/<ton-utilisateur>/<nom-du-repo>
theme:
  name: material
  features:
    - navigation.expand
    - navigation.top
    - content.code.annotate
    - content.tabs.link
  language: fr

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Accueil: index.md
  - Chapitre 1: chapitre1.md
  - Chapitre 2: chapitre2.md
